# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy website

on:
  push:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install NodeJS
      uses: actions/setup-node@v2-beta
      with: 
        node-version: 12
    - name: Install Surge
      run: npm install -g surge
    - name: Run Surge
      run: ./ bootcamp-react-app647123456.surge.sh --token ${{secrets.SURGE_TOKEN}}
      
     
    
   
